name: Go Backend CI/CD
on:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go version 1.23.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Run Tests
        env:
          ENV: cicd
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb?sslmode=disable
          JWT_SECRET_KEY: secretkey
        run: go test ./tests -v
